name: pages-build-deployment

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up Node.js for the workflow
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Prepare build outputs
        run: |
          mkdir -p ${{ env.OUTPUT_DIR }}
          mkdir -p ${{ env.OUTPUT_DIR }}/counter
          cp counter/index.html ${{ env.OUTPUT_DIR }}/counter/index.html

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.OUTPUT_DIR }}/

    env:
      OUTPUT_DIR: build_outputs_folder
